### PR TITLE
Clean up the menubar

### PR DESCRIPTION
**Pull request by tansly**
Progress on #4. Removes share, community and login related buttons from the menubar.

### CODE REVIEW

**Comment by tansly** [comment]
Removed unused variables. Tests should pass now.

**Comment by tansly** [comment]
Removed the buttons/components from the menubar; they are not rendered now. But I did not remove the related code completely, i.e. their definitions remain in their code files. They may be useful in the future. If anyone thinks they should be removed too, ping me.

**Comment by tansly** [comment]
Fixed the lint errors, integration tests are failing now. Investigate later.

**Comment by tansly** [comment]
Tests are passing now.

There is a problem, though. I can't figure out why the default project title is still "Scratch Project". 8feb85d940844d8d41f9cb51d1c7d48abd29b5ce should have dealt with that. (See the change in src/containers/gui.jsx) I've searched everywhere but I can't find the string "Scratch Project" anywhere else in the GUI code. Where does it come from?

**Comment by tansly** [comment]
Turns out it comes from the localization code: https://github.com/LLK/scratch-l10n/blob/36cbe734e61d2652e285b8e6ba35a588898083e5/editor/interface/en.json#L222

What to do about it? It looks like l10n stuff will be a pain...

**Comment by tansly** [comment]
I don't like https://github.com/FBDY/bb-gui/pull/14/commits/7eba17ff74ba66325e7ded5142e7e3484251b80b, but I really don't want #15 to block this, so I made this dirty hack. Please don't kill me.

**Comment by tansly** [comment]
It looks good to me, except the colors and the logo remains. But I think we should deal with them in #13 anyways; this is just a cleanup effort. Whaddya think?

**Comment by tansly** [comment]
Well, the "pr" build of Travis was passing, but "push" build was failing (with a timeout after 10 minutes) for no apparent reason. It is very strange that it passed after restarting it twice. I don't think there is anything we can immediately do about it though. Note that LLK repos also get similar failures ([467583300](https://travis-ci.org/LLK/scratch-gui/builds/467583300)) once in a while; maybe there is a problem at their front, who knows?

Anyways, once again, looks good to me. If we are not satisfied, we can rerun the build a few more times and see what we can see. Doesn't look likely but maybe we can catch some patterns.

PS: I've found this: https://stackoverflow.com/questions/41524861/travis-failed-push-but-passed-pr, but it doesn't seem to fit in to our case.

**Review by bozbalci — APPROVED** [review]
🚀💯 

We should really find a solution for the i18n issue though, as I believe we will run into a lot of such strings retrieved in that manner.

**Pull request merged**
