### PR TITLE
Disable "Welcome to the Scratch" popup message

### PR DESCRIPTION
**Pull request by akca**
image

### CODE REVIEW

**Review by bozbalci — APPROVED** [review]
LGTM

**Comment by tansly** [comment]
I'll try to check on this tomorrow. Let's see what I can dig up.

**Comment by tansly** [comment]
Turns out the integration tests depend on this window being opened; they start by clicking the "Try It" button. Removing such click actions fixes the tests.

I think we can merge this, if everyone is happy.

**Comment by bozbalci** [comment]
@tansly removal of the "Try It" tests sounds like the best idea. I think we can merge this.

**Pull request merged**
