### PR TITLE
Page title has been reworked.

### LINKED ISSUE #16: Favicon and the page title should be changed
We should also change the favicon and the page title for #4.

### PR DESCRIPTION
**Pull request by Doruk-Coskun**
### Resolves

#16 Page title fixed. Favicon still needs work.

### Proposed Changes

Changes Page titles from Scratch to BBGE

### Reason for Changes

It was required to customize our Scratch fork.

### Test Coverage

Tested page title with Safari and Google Chrome on macOS 10.14.1

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [x] Chrome 
 * [ ] Firefox 
 * [x] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

**Comment by bozbalci** [comment]
LGTM 🚀 💯

**Review by bozbalci — APPROVED** [review]
LGTM 💯

**Comment by tansly** [comment]
Changed the favicon file at `static/favicon.ico` but the favicon did not change. Looking into it.

**Comment by tansly** [comment]
It was cached by my browser, apparently (thanks @bozbalci). Merging.

**Pull request merged**
